project_id = "kpighaiggdmyujjqzawm"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true
ip_version = 4
port = 54323
max_header_length = 4096

[studio]
enabled = true
port = 54324
api_url = "http://127.0.0.1:54321"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54325
api_port = 54326
smtp_port = 54327

[storage]
enabled = true
port = 54328
file_size_limit = "50MiB"
image_transformation.enabled = true

[auth]
enabled = true
port = 54327
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://127.0.0.1:3000"]
jwt_expiry = 3600
enable_signup = true
enable_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false
secure_nonce = true

[auth.sms]
enable_signup = false
enable_confirmations = false
secure_phone_change = true

[functions.send-sms]
verify_jwt = false

[functions.bml-payment-webhook]
verify_jwt = false

[functions.notify-fee-assignment]
verify_jwt = false

[functions.check-overdue-fees]
verify_jwt = false

[edge-runtime]
enabled = true
policy = "per_request"
inspector_port = 8083