// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpighaiggdmyujjqzawm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtwaWdoYWlnZ2RteXVqanF6YXdtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNzM1MzgsImV4cCI6MjA2OTY0OTUzOH0.MI2Tl9R1BrYLK_w7Y0rZH4A5schAldhrvTst_ixWzKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});